name: PureGym Attendance Logger

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  log-attendance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PureGym Logger
      env:
        PUREGYM_EMAIL: ${{ secrets.PUREGYM_EMAIL }}
        PUREGYM_PASS: ${{ secrets.PUREGYM_PASS }}
      run: python main.py

    - name: Upload gym_log.csv artifact
      uses: actions/upload-artifact@v4
      with:
        name: gym_log
        path: gym_log.csv
