name: PureGym Attendance Logger

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  log-attendance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # This step attempts to download the artifact from the most recent successful run
    # 'name: gym_log' matches the name used in the upload step
    # 'path: .' downloads it to the current working directory, where main.py expects it
    # 'continue-on-error: true' ensures the workflow doesn't fail if no previous artifact exists (e.g., on the first run)
    - name: Download previous gym_log artifact
      uses: actions/download-artifact@v4
      with:
        name: gym_log
        path: gym_log.csv
      continue-on-error: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PureGym Logger
      env:
        PUREGYM_EMAIL: ${{ secrets.PUREGYM_EMAIL }}
        PUREGYM_PASS: ${{ secrets.PUREGYM_PASS }}
      run: python main.py

    - name: Upload gym_log.csv artifact
      uses: actions/upload-artifact@v4
      with:
        name: gym_log
        path: gym_log.csv
        overwrite: true
